# Generated by Django 4.2.7 on 2026-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_check_list_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='IS_ACTIVE',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True),
        ),
        migrations.AddField(
            model_name='year',
            name='IS_ACTIVE',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True),
        ),
    ]
