# Generated by Django 4.2.7 on 2026-02-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_semester_is_active_year_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='CODE',
            field=models.CharField(db_column='CODE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('INSTITUTE', 'CODE')},
        ),
    ]
