# Generated by Django 4.2.7 on 2026-02-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_program_code_alter_program_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='CODE',
            field=models.CharField(db_column='CODE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('PROGRAM', 'CODE')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('YEAR', 'SEMESTER')},
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('BRANCH', 'YEAR')},
        ),
    ]
