# Generated by Django 4.2.7 on 2026-02-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_branch_code_alter_branch_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACADEMIC_YEAR',
        ),
    ]
