# Generated by Django 4.2.7 on 2026-02-14 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_delete_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MENU_ITEM_MASTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('MENU_ID', models.AutoField(db_column='MENU_ID', primary_key=True, serialize=False)),
                ('LABEL', models.CharField(db_column='LABEL', max_length=100)),
                ('PATH', models.CharField(blank=True, db_column='PATH', max_length=255, null=True)),
                ('IS_SIDEBAR_ITEM', models.BooleanField(db_column='IS_SIDEBAR_ITEM', default=True)),
                ('SORT_ORDER', models.IntegerField(db_column='SORT_ORDER', default=0)),
                ('PARENT_MENU', models.ForeignKey(blank=True, db_column='PARENT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.menu_item_master')),
            ],
            options={
                'verbose_name': 'Menu Item Master',
                'verbose_name_plural': 'Menu Item Masters',
                'db_table': '"ADMIN"."MENU_ITEM_MASTER"',
                'ordering': ['SORT_ORDER', 'MENU_ID'],
            },
        ),
        migrations.CreateModel(
            name='USER_FORM_PERMISSION',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('PERMISSION_ID', models.AutoField(db_column='PERMISSION_ID', primary_key=True, serialize=False)),
                ('CAN_VIEW', models.BooleanField(db_column='CAN_VIEW', default=False)),
                ('CAN_ADD', models.BooleanField(db_column='CAN_ADD', default=False)),
                ('CAN_EDIT', models.BooleanField(db_column='CAN_EDIT', default=False)),
                ('CAN_DELETE', models.BooleanField(db_column='CAN_DELETE', default=False)),
                ('MENU_ITEM', models.ForeignKey(db_column='MENU_ID', on_delete=django.db.models.deletion.CASCADE, to='accounts.menu_item_master')),
                ('USER', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='form_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Form Permission',
                'verbose_name_plural': 'User Form Permissions',
                'db_table': '"ADMIN"."USER_FORM_PERMISSIONS"',
                'unique_together': {('USER', 'MENU_ITEM')},
            },
        ),
    ]
