# Generated by Django 4.2.7 on 2026-02-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_check_list_documents'),
        ('establishments', '0009_alter_employee_master_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_master',
            name='CATEGORY',
            field=models.ForeignKey(blank=True, db_column='CATEGORY_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='DATE_OF_BIRTH',
            field=models.DateField(blank=True, db_column='DATE_OF_BIRTH', null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='DATE_OF_JOIN',
            field=models.DateField(blank=True, db_column='DATE_OF_JOIN', null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='MARITAL_STATUS',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], db_column='MARITAL_STATUS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='MOBILE_NO',
            field=models.CharField(blank=True, db_column='MOBILE_NO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='PERMANENT_ADDRESS',
            field=models.TextField(blank=True, db_column='PERMANENT_ADDRESS', null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='PERMANENT_CITY',
            field=models.CharField(blank=True, db_column='PERMANENT_CITY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='PERMANENT_PIN',
            field=models.CharField(blank=True, db_column='PERMANENT_PIN', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='SEX',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_column='SEX', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='SHIFT',
            field=models.ForeignKey(blank=True, db_column='SHIFT', null=True, on_delete=django.db.models.deletion.PROTECT, to='establishments.shift_master'),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='STATUS',
            field=models.ForeignKey(blank=True, db_column='STATUS_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_status', to='establishments.status_master'),
        ),
    ]
