# Generated by Django 4.2.7 on 2026-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0010_alter_employee_master_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_qualification',
            name='COLLEGE_NAME',
            field=models.CharField(blank=True, db_column='COLLEGE_NAME', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='DEGREE',
            field=models.CharField(blank=True, db_column='DEGREE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='DIVISION',
            field=models.CharField(blank=True, db_column='DIVISION', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='OBTAINED_MARKS',
            field=models.DecimalField(blank=True, db_column='OBTAINED_MARKS', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='PASSING_DATE',
            field=models.DateField(blank=True, db_column='PASSING_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='PASSING_MONTH',
            field=models.CharField(blank=True, db_column='PASSING_MONTH', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='PASSING_YEAR',
            field=models.CharField(blank=True, db_column='PASSING_YEAR', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='PERCENTAGE',
            field=models.DecimalField(blank=True, db_column='PERCENTAGE', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='TOTAL_MARKS',
            field=models.DecimalField(blank=True, db_column='TOTAL_MARKS', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_qualification',
            name='UNIVERSITY_BOARD',
            field=models.CharField(blank=True, db_column='UNIVERSITY_BOARD', max_length=200, null=True),
        ),
    ]
