# Generated by Django 4.2.7 on 2026-02-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='STUDENT',
            field=models.ForeignKey(blank=True, db_column='STUDENT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student_master'),
        ),
        migrations.AlterField(
            model_name='student_roll_number_details',
            name='STUDENT',
            field=models.ForeignKey(blank=True, db_column='STUDENT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_number_details', to='student.student_master'),
        ),
    ]
