# Generated by Django 4.2.7 on 2026-02-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_details_student_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='check_list_documents',
            table='"STUDENT"."CHECK_LIST_DOCUMENTS"',
        ),
    ]
