# Generated by Django 4.2.7 on 2026-02-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_academic_term_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_year',
            name='YEAR',
        ),
        migrations.AddField(
            model_name='academic_year',
            name='ACADEMIC_YEAR',
            field=models.CharField(db_column='YEAR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academic_year',
            name='INSTITUTE',
            field=models.CharField(db_column='INSTITUTE_ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academic_year',
            name='UNIVERSITY',
            field=models.CharField(db_column='UNIVERSITY_ID', max_length=50, null=True),
        ),
    ]
