
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_academic_year_year_and_more'),
    ]

    operations = [
        # Drop constraints for EXAMINATIONS
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."EXAMINATIONS" DROP CONSTRAINT IF EXISTS "EXAMINATIONS_CREATED_BY_f69e13b2_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."EXAMINATIONS" DROP CONSTRAINT IF EXISTS "EXAMINATIONS_DELETED_BY_e72771c3_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."EXAMINATIONS" DROP CONSTRAINT IF EXISTS "EXAMINATIONS_UPDATED_BY_2371b4b0_fk_USERS_USER_ID";'),
        
        # Drop constraints for CURRICULUM
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."CURRICULUM" DROP CONSTRAINT IF EXISTS "CURRICULUM_CREATED_BY_67c46eb2_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."CURRICULUM" DROP CONSTRAINT IF EXISTS "CURRICULUM_DELETED_BY_6ffe97e5_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."CURRICULUM" DROP CONSTRAINT IF EXISTS "CURRICULUM_UPDATED_BY_429c3409_fk_USERS_USER_ID";'),
        
        # Drop constraints for COURSES
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."COURSES" DROP CONSTRAINT IF EXISTS "COURSES_CREATED_BY_185e8682_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."COURSES" DROP CONSTRAINT IF EXISTS "COURSES_DELETED_BY_5b356e62_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."COURSES" DROP CONSTRAINT IF EXISTS "COURSES_UPDATED_BY_1ea1bb8e_fk_USERS_USER_ID";'),
        
        # Drop constraints for ACADEMIC_YEARS
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."ACADEMIC_YEARS" DROP CONSTRAINT IF EXISTS "ACADEMIC_YEARS_CREATED_BY_de386659_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."ACADEMIC_YEARS" DROP CONSTRAINT IF EXISTS "ACADEMIC_YEARS_DELETED_BY_d8eff50d_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."ACADEMIC_YEARS" DROP CONSTRAINT IF EXISTS "ACADEMIC_YEARS_UPDATED_BY_b7e51ddd_fk_USERS_USER_ID";'),
        
        # Drop constraints for ACADEMIC_TERMS
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."ACADEMIC_TERMS" DROP CONSTRAINT IF EXISTS "ACADEMIC_TERMS_CREATED_BY_560fe643_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."ACADEMIC_TERMS" DROP CONSTRAINT IF EXISTS "ACADEMIC_TERMS_DELETED_BY_3af6db46_fk_USERS_USER_ID";'),
        migrations.RunSQL('ALTER TABLE "ACADEMIC"."ACADEMIC_TERMS" DROP CONSTRAINT IF EXISTS "ACADEMIC_TERMS_UPDATED_BY_b07f5324_fk_USERS_USER_ID";'),
    ]
